redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\Flores Boys\\.antigravity\\hymnify"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/api/songbase/*"
to = "https://songbase.life/api/v2/:splat"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]